// <auto-generated />
using Mango.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231108121508_seedCoupontable")]
    partial class seedCoupontable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.ToTable("Coupones");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "1000A",
                            DiscountAmount = 100.0,
                            MinAmount = 500
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "1000B",
                            DiscountAmount = 10.0,
                            MinAmount = 50
                        },
                        new
                        {
                            CouponId = 3,
                            CouponCode = "1000C",
                            DiscountAmount = 150.0,
                            MinAmount = 500
                        },
                        new
                        {
                            CouponId = 4,
                            CouponCode = "1000D",
                            DiscountAmount = 140.0,
                            MinAmount = 200
                        },
                        new
                        {
                            CouponId = 5,
                            CouponCode = "1000E",
                            DiscountAmount = 10.0,
                            MinAmount = 50
                        },
                        new
                        {
                            CouponId = 6,
                            CouponCode = "1000F",
                            DiscountAmount = 180.0,
                            MinAmount = 350
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
